algo=input('Digite algo: ')
print(type(algo))
print('Número:', algo.isalnum())
print('Alfabeto:', algo.isalpha())
print('Ascii: ',algo.isascii())
print(algo.isdecimal())
print(algo.isdigit())
print(algo.isidentifier())
print(algo.islower())
print(algo.isnumeric())
print(algo.isprintable())
print(algo.isspace())
print(algo.istitle())
print(algo.isupper())
print()